name = "JJUtils"
uuid = "c29d8188-4008-4bd5-9bee-3588d17fb181"
authors = ["Jakob R. Juegens"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
